# Generated by Django 4.2.1 on 2023-05-25 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='upload_file',
            field=models.FileField(null=True, upload_to='audio'),
        ),
    ]
