# Generated by Django 4.2.1 on 2023-06-01 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_comment_post_id_alter_comment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='total_comments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='music',
            name='total_likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='music',
            name='total_played',
            field=models.IntegerField(default=0),
        ),
    ]
