# Generated by Django 4.2.1 on 2023-06-01 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_music_total_comments_music_total_likes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_id',
            new_name='id',
        ),
    ]
