# Generated by Django 4.2.1 on 2023-06-01 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_rename_id_post_post_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='postcomment',
            unique_together={('post', 'comment')},
        ),
    ]
