# Generated by Django 4.2.1 on 2023-06-01 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_postcomment_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='postcomment',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='post',
            name='comments',
        ),
    ]
