# Generated by Django 4.2.1 on 2023-07-12 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_usersonginteraction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='total_comments',
        ),
    ]
