# Generated by Django 3.2.12 on 2023-05-22 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('musics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlibrary',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userhistory',
            name='history_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musics.history'),
        ),
        migrations.AddField(
            model_name='userhistory',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='library',
            name='music_id',
            field=models.ManyToManyField(to='posts.Music'),
        ),
        migrations.AddField(
            model_name='history',
            name='music_id',
            field=models.ManyToManyField(to='posts.Music'),
        ),
    ]
