# Generated by Django 3.2.12 on 2023-05-17 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_id', models.IntegerField(null=True)),
                ('user_id', models.IntegerField(null=True)),
                ('post_id', models.IntegerField(null=True)),
                ('content', models.CharField(max_length=255)),
                ('date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='friendRecommend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id_1', models.IntegerField(null=True)),
                ('user_id_2', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(null=True)),
                ('music_id', models.IntegerField(null=True)),
                ('date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(null=True)),
                ('music_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_id', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=255)),
                ('img', models.ImageField(null=True, upload_to='static/img')),
                ('total_played', models.IntegerField(null=True)),
                ('total_likes', models.IntegerField(null=True)),
                ('total_comments', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='musicRecommend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(null=True)),
                ('music_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.IntegerField(null=True)),
                ('user_id', models.IntegerField(null=True)),
                ('music_id', models.IntegerField(null=True)),
                ('content', models.CharField(max_length=255)),
                ('date', models.DateField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='userregister',
            name='ava',
            field=models.ImageField(null=True, upload_to='static/img'),
        ),
        migrations.AddField(
            model_name='userregister',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='userregister',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=10),
        ),
        migrations.AddField(
            model_name='userregister',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userregister',
            name='wall',
            field=models.ImageField(null=True, upload_to='static/img'),
        ),
    ]
