# Generated by Django 3.2.12 on 2023-05-22 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userregister',
            old_name='ava',
            new_name='avatar',
        ),
        migrations.RenameField(
            model_name='userregister',
            old_name='dob',
            new_name='birthday',
        ),
    ]
