# Generated by Django 4.2.1 on 2023-05-29 09:36

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0002_auto_20230522_1225'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnLibraryPermission',
            fields=[
            ],
            options={
                'permissions': (('verify_library_owner', 'Can verify library owner'),),
                'proxy': True,
                'default_permissions': (),
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.permission',),
            managers=[
                ('objects', django.contrib.auth.models.PermissionManager()),
            ],
        ),
    ]
