# Generated by Django 4.2.1 on 2023-05-30 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_ownlibrarypermission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OwnLibraryPermission',
        ),
    ]
